<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>WindowsLab.Tweaks</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WindowsLab.Core\WindowsLab.Core.csproj" />
    <ProjectReference Include="..\WindowsLab.Backup\WindowsLab.Backup.csproj" />
  </ItemGroup>
</Project>
