namespace WindowsLab.Core;

public static class Loc
{
    private static string _lang = "es";

    public static string Language
    {
        get => _lang;
        set => _lang = string.Equals(value, "en", StringComparison.OrdinalIgnoreCase) ? "en" : "es";
    }

    public static bool IsEnglish => _lang == "en";

    public static string T(string key) =>
        (IsEnglish ? En : Es).TryGetValue(key, out var v) ? v : key;

    private static readonly Dictionary<string, string> Es = new(StringComparer.OrdinalIgnoreCase)
    {
        ["nav.home"] = "Inicio",
        ["nav.prep"] = "CONFIGURAR",
        ["nav.adv"] = "SUPERVISAR",
        ["nav.maintain"] = "MANTENER",
        ["nav.config"] = "Packs / stacks",
        ["nav.resources"] = "Herramientas",
        ["nav.performance"] = "Performance",
        ["nav.system"] = "Sistema",
        ["nav.security"] = "Seguridad",
        ["nav.tweaks"] = "Tweaks",
        ["nav.advice"] = "Consejos",
        ["nav.checklist"] = "Checklist",
        ["nav.apps"] = "Aplicaciones",
        ["nav.settings"] = "Ajustes",
        ["subtitle"] = "1.0 — configurar Windows con backup y control",
        ["menu.file"] = "Archivo",
        ["menu.view"] = "Ver",
        ["menu.tools"] = "Herramientas",
        ["menu.help"] = "Ayuda",
        ["menu.exit"] = "Salir",
        ["menu.backups"] = "Respaldos",
        ["menu.updates"] = "Buscar actualizaciones",
        ["menu.about"] = "Acerca de WindowsLab",
        ["menu.releases"] = "Releases en GitHub",
        ["profile"] = "Perfil",
        ["theme.label"] = "Tema",
        ["theme.dark"] = "Oscuro",
        ["theme.light"] = "Claro",
        ["theme.system"] = "Sistema",
        ["apps.hint"] = "Ranking multi-eje (privacidad, telemetría, seguridad, rendimiento, ecosistema) según perfil. Instalar usa winget con confirmación. No fija el navegador predeterminado.",
        ["apps.install"] = "Instalar selección",
        ["apps.defaults"] = "Apps predeterminadas (Windows)",
        ["apps.filter"] = "Categoría",
        ["home.morePacks"] = "Más packs",
        ["home.probes"] = "Sondas",
        ["home.details"] = "Detalles del equipo",
        ["home.tools"] = "Herramientas rápidas",
        ["home.modes"] = "Montaje rápido",
        ["home.modesHint"] = "Elige un modo o stack. Abre el pack para revisar y aplicar (HKCU; sistema con opt-in).",
        ["home.stacks"] = "Stacks de máquina",
        ["mode.gaming"] = "Gaming",
        ["mode.gaming.sub"] = "Game Mode, menos DVR, rendimiento",
        ["mode.optimized"] = "Optimizada",
        ["mode.optimized.sub"] = "Máximo rendimiento + menos chrome",
        ["mode.dev"] = "Desarrollo",
        ["mode.dev.sub"] = "Rutas largas, explorador, toolchain",
        ["mode.balanced"] = "Equilibrada",
        ["mode.balanced.sub"] = "Privacidad + ajustes seguros",
        ["mode.empresa"] = "Empresa",
        ["mode.empresa.sub"] = "Puesto de oficina: privacidad, Edge, Office",
        ["mode.pruebas"] = "Pruebas / Lab",
        ["mode.pruebas.sub"] = "Lab VM: explorador, git, PowerShell",
        ["home.loading"] = "Cargando inventario y catálogo…",
        ["home.loadingHint"] = "La primera carga puede tardar en VMware. Si falla: %LocalAppData%\\WindowsLab\\crash.log",
        ["config.hint"] = "Pack o stack elegido. Activar abre Windows. Aplicar escribe tweaks elegibles (con backup).",
        ["btn.activatePack"] = "Abrir en Windows",
        ["btn.simulatePack"] = "Simular pack",
        ["btn.activateRow"] = "Abrir fila",
        ["btn.applyPack"] = "Aplicar pack (HKCU)",
        ["btn.applyDisabled"] = "Solo ítems elegibles: HKCU LOW OFFICIAL/STRONG, o sistema con opt-in.",
        ["btn.applyTweak"] = "Aplicar selección",
        ["resources.title"] = "Herramientas",
        ["resources.hint"] = "BGInfo, overlays y accesos. El dashboard vivo está en Performance.",
        ["resources.liveHint"] = "Vista rápida (Performance para procesos agrupados):",
        ["btn.openPerformance"] = "Abrir Performance",
        ["settings.systemApply"] = "Apply de sistema",
        ["settings.systemApplyHint"] = "HKLM / Worker requieren opt-in (VM lab o casilla). El apply HKCU sigue disponible.",
        ["perf.title"] = "Performance",
        ["perf.hint"] = "Actualiza cada 2 s. Sin matar procesos. Standby ≠ RAM desperdiciada.",
        ["perf.cpu"] = "CPU",
        ["perf.ram"] = "RAM",
        ["perf.disk"] = "Disco",
        ["perf.ram.avail"] = "Disponible",
        ["perf.disk.free"] = "libre",
        ["perf.filter"] = "Grupo",
        ["perf.sortHint"] = "Top 25 por working set",
        ["perf.footer"] = "Métricas en vivo (no modifican el sistema). No vaciamos standby ni matamos Defender/Search/SysMain. Defender realtime OFF = D021 (gated).",
        ["perf.group.all"] = "Todos",
        ["perf.group.windows"] = "Windows",
        ["perf.group.microsoft"] = "Microsoft",
        ["perf.group.external"] = "Externas",
        ["btn.desktopInfo"] = "DesktopInfo overlay",
        ["btn.bginfo"] = "BGInfo oficial (Sysinternals)",
        ["btn.bginfo.activate"] = "Activar BGInfo",
        ["btn.bginfo.docs"] = "Docs BGInfo",
        ["btn.activateWindows"] = "Activar Windows",
        ["btn.libreoffice"] = "Descargar LibreOffice",
        ["btn.windowsSecurity"] = "Seguridad de Windows",
        ["btn.windowsSecurity.tip"] = "Abre Seguridad de Windows (UI). Para automatizar: botón «Defender tiempo real OFF» (D021, HIGH).",
        ["btn.windowsSecurity.status"] = "Abierta Seguridad de Windows.",
        ["btn.windowsSecurity.fail"] = "No se pudo abrir Seguridad de Windows.",
        ["btn.defenderRealtimeOff"] = "Defender tiempo real OFF",
        ["btn.defenderRealtimeOff.tip"] = "D021: política HKLM DisableRealtimeMonitoring=1. No mata MsMpEng. Requiere allow system apply + doble confirmación. Nunca recomendado.",
        ["btn.defenderRealtimeOff.confirm1"] = "Esto reduce la protección en tiempo real de Microsoft Defender (política HKLM).\nNo mata el proceso MsMpEng; no toca DiagTrack/SysMain/Search.\n\n¿Continuar con la primera confirmación?",
        ["btn.defenderRealtimeOff.confirm2"] = "Segunda confirmación (obligatoria):\nAceptas el impacto de seguridad y aplicar security.defender-realtime-off vía Worker/UAC?\nSi Tamper Protection bloquea el write, abre Seguridad de Windows manualmente.",
        ["btn.defenderRealtimeOff.reboot"] = "El tweak marca requiresReboot. Reinicia para que la política surta efecto.\n¿Abrir Configuración → Sistema → Recuperación (reinicio)?",
        ["btn.defenderRealtimeOff.done"] = "Apply Defender realtime-off: {0}",
        ["btn.defenderRealtimeOff.cancelled"] = "Cancelado (Defender realtime-off).",
        ["security.confirm2"] = "Segunda confirmación (obligatoria, D021):\nAceptas el impacto de seguridad de los tweaks listados?\nSi Tamper Protection bloquea el write, abre Seguridad de Windows.",
        ["security.cancelled"] = "Cancelado (impacto de seguridad).",
        ["apply.rebootPrompt"] = "Uno o más tweaks requieren reinicio.\n¿Abrir Configuración → Sistema → Recuperación?",
        ["advice.hint"] = "Consejos del perfil + guía de procesos. No matamos Search/SysMain. Defender opt-out solo vía D021 (nunca recomendado).",
        ["advice.bg.title"] = "Procesos en segundo plano",
        ["settings.channels"] = "Canales de configuración",
        ["settings.channelsHint"] = "Preferencias UI + backups de apply en %LocalAppData%\\WindowsLab\\backups.",
        ["btn.openUser"] = "Abrir carpeta de usuario",
        ["btn.openMachine"] = "Abrir carpeta de máquina",
        ["lang.label"] = "Idioma",
        ["telemetry.limit"] = "En Home/Pro no existe telemetría cero: el mínimo oficial es Required (1).",
        ["tools.godmode"] = "Modo Dios (todas las applets)",
        ["tools.godmodeHow"] = "Abre el panel clásico con todas las opciones. No es un bypass.",
        ["tweaks.hint"] = "Vista experta (tabla). Para flujo simple usa Checklist → Activar. Apply = HKCU con backup.",
        ["checklist.hint"] = "Checklist simple: Activar abre Configuración o aplica HKCU si está enlazado.",
        ["update.title"] = "Actualizaciones",
        ["update.check"] = "Buscar actualizaciones",
        ["update.open"] = "Abrir releases en GitHub",
        ["update.checking"] = "Consultando GitHub…",
        ["update.version"] = "Versión instalada: {0}",
    };

    private static readonly Dictionary<string, string> En = new(StringComparer.OrdinalIgnoreCase)
    {
        ["nav.home"] = "Home",
        ["nav.prep"] = "CONFIGURE",
        ["nav.adv"] = "MONITOR",
        ["nav.maintain"] = "MAINTAIN",
        ["nav.config"] = "Packs / stacks",
        ["nav.resources"] = "Tools",
        ["nav.performance"] = "Performance",
        ["nav.system"] = "System",
        ["nav.security"] = "Security",
        ["nav.tweaks"] = "Tweaks",
        ["nav.advice"] = "Advice",
        ["nav.checklist"] = "Checklist",
        ["nav.apps"] = "Applications",
        ["nav.settings"] = "Settings",
        ["subtitle"] = "1.0 — configure Windows with backup and control",
        ["menu.file"] = "File",
        ["menu.view"] = "View",
        ["menu.tools"] = "Tools",
        ["menu.help"] = "Help",
        ["menu.exit"] = "Exit",
        ["menu.backups"] = "Backups",
        ["menu.updates"] = "Check for updates",
        ["menu.about"] = "About WindowsLab",
        ["menu.releases"] = "GitHub releases",
        ["profile"] = "Profile",
        ["theme.label"] = "Theme",
        ["theme.dark"] = "Dark",
        ["theme.light"] = "Light",
        ["theme.system"] = "System",
        ["apps.hint"] = "Multi-axis ranking (privacy, telemetry, security, performance, ecosystem) by profile. Install uses winget with confirmation. Does not set the default browser.",
        ["apps.install"] = "Install selection",
        ["apps.defaults"] = "Default apps (Windows)",
        ["apps.filter"] = "Category",
        ["home.morePacks"] = "More packs",
        ["home.probes"] = "Probes",
        ["home.details"] = "Machine details",
        ["home.tools"] = "Quick tools",
        ["home.modes"] = "Quick setup",
        ["home.modesHint"] = "Pick a mode or stack. Opens the pack to review and apply (HKCU; system with opt-in).",
        ["home.stacks"] = "Machine stacks",
        ["mode.gaming"] = "Gaming",
        ["mode.gaming.sub"] = "Game Mode, less DVR, performance",
        ["mode.optimized"] = "Optimized",
        ["mode.optimized.sub"] = "Max performance + less chrome",
        ["mode.dev"] = "Developer",
        ["mode.dev.sub"] = "Long paths, Explorer, toolchain",
        ["mode.balanced"] = "Balanced",
        ["mode.balanced.sub"] = "Privacy + safe tweaks",
        ["mode.empresa"] = "Business",
        ["mode.empresa.sub"] = "Office seat: privacy, Edge, LibreOffice",
        ["mode.pruebas"] = "Lab / Test",
        ["mode.pruebas.sub"] = "Lab VM: Explorer, git, PowerShell",
        ["home.loading"] = "Loading inventory and catalog…",
        ["home.loadingHint"] = "First load may take a few seconds in VMware. On failure: %LocalAppData%\\WindowsLab\\crash.log",
        ["config.hint"] = "Chosen pack or stack. Open in Windows, or Apply writes eligible tweaks (with backup).",
        ["btn.activatePack"] = "Open in Windows",
        ["btn.simulatePack"] = "Simulate pack",
        ["btn.activateRow"] = "Open row",
        ["btn.applyPack"] = "Apply pack (HKCU)",
        ["btn.applyDisabled"] = "Eligible items: HKCU LOW OFFICIAL/STRONG, or system with opt-in.",
        ["btn.applyTweak"] = "Apply selection",
        ["resources.title"] = "Tools",
        ["resources.hint"] = "BGInfo, overlays, and shortcuts. Live dashboard is under Performance.",
        ["resources.liveHint"] = "Quick peek (open Performance for grouped processes):",
        ["btn.openPerformance"] = "Open Performance",
        ["settings.systemApply"] = "System apply",
        ["settings.systemApplyHint"] = "HKLM / Worker need opt-in (lab VM or checkbox). HKCU apply stays available.",
        ["perf.title"] = "Performance",
        ["perf.hint"] = "Refreshes every 2 s. No process kill. Standby ≠ wasted RAM.",
        ["perf.cpu"] = "CPU",
        ["perf.ram"] = "RAM",
        ["perf.disk"] = "Disk",
        ["perf.ram.avail"] = "Available",
        ["perf.disk.free"] = "free",
        ["perf.filter"] = "Group",
        ["perf.sortHint"] = "Top 25 by working set",
        ["perf.footer"] = "Live metrics (do not change the system). We do not empty standby or kill Defender/Search/SysMain. Defender realtime OFF = D021 (gated).",
        ["perf.group.all"] = "All",
        ["perf.group.windows"] = "Windows",
        ["perf.group.microsoft"] = "Microsoft",
        ["perf.group.external"] = "External",
        ["btn.desktopInfo"] = "DesktopInfo overlay",
        ["btn.bginfo"] = "Official BGInfo (Sysinternals)",
        ["btn.bginfo.activate"] = "Enable BGInfo",
        ["btn.bginfo.docs"] = "BGInfo docs",
        ["btn.activateWindows"] = "Activate Windows",
        ["btn.libreoffice"] = "Download LibreOffice",
        ["btn.windowsSecurity"] = "Windows Security",
        ["btn.windowsSecurity.tip"] = "Opens Windows Security (UI). To automate: «Defender realtime OFF» (D021, HIGH).",
        ["btn.windowsSecurity.status"] = "Opened Windows Security.",
        ["btn.windowsSecurity.fail"] = "Could not open Windows Security.",
        ["btn.defenderRealtimeOff"] = "Defender realtime OFF",
        ["btn.defenderRealtimeOff.tip"] = "D021: HKLM policy DisableRealtimeMonitoring=1. Does not kill MsMpEng. Needs system-apply allow + double confirm. Never recommended.",
        ["btn.defenderRealtimeOff.confirm1"] = "This reduces Microsoft Defender real-time protection (HKLM policy).\nDoes not kill MsMpEng; does not touch DiagTrack/SysMain/Search.\n\nContinue with the first confirmation?",
        ["btn.defenderRealtimeOff.confirm2"] = "Second confirmation (required):\nAccept the security impact and apply security.defender-realtime-off via Worker/UAC?\nIf Tamper Protection blocks the write, open Windows Security manually.",
        ["btn.defenderRealtimeOff.reboot"] = "This tweak requires a reboot for the policy to take effect.\nOpen Settings → System → Recovery (restart)?",
        ["btn.defenderRealtimeOff.done"] = "Apply Defender realtime-off: {0}",
        ["btn.defenderRealtimeOff.cancelled"] = "Cancelled (Defender realtime-off).",
        ["security.confirm2"] = "Second confirmation (required, D021):\nAccept the security impact of the listed tweaks?\nIf Tamper Protection blocks the write, open Windows Security.",
        ["security.cancelled"] = "Cancelled (security impact).",
        ["apply.rebootPrompt"] = "One or more tweaks require a reboot.\nOpen Settings → System → Recovery?",
        ["advice.hint"] = "Profile advice + background tips. We do not kill Search/SysMain. Defender opt-out only via D021 (never recommended).",
        ["advice.bg.title"] = "Background processes",
        ["settings.channels"] = "Configuration channels",
        ["settings.channelsHint"] = "UI prefs + apply backups under %LocalAppData%\\WindowsLab\\backups.",
        ["btn.openUser"] = "Open user folder",
        ["btn.openMachine"] = "Open machine folder",
        ["lang.label"] = "Language",
        ["telemetry.limit"] = "Home/Pro cannot fully disable telemetry: official floor is Required (1).",
        ["tools.godmode"] = "God Mode (all applets)",
        ["tools.godmodeHow"] = "Opens the classic panel with every Control Panel applet. Not a bypass.",
        ["tweaks.hint"] = "Expert table view. For a simple flow use Checklist → Activate. Apply = HKCU with backup.",
        ["checklist.hint"] = "Simple checklist: Activate opens Settings or applies linked HKCU tweaks.",
        ["update.title"] = "Updates",
        ["update.check"] = "Check for updates",
        ["update.open"] = "Open GitHub releases",
        ["update.checking"] = "Checking GitHub…",
        ["update.version"] = "Installed version: {0}",
    };
}
